#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

  # the "app_page_number" route name is not important yet
app_page_page1:
    path: /page
    controller: App\Controller\ArticleController::articles

    
    # the "app_page_number" route name is not important yet
app_page_page2:
    path: /page/{id}
    controller: App\Controller\Page1::article

# the "app_page_number" route name is not important yet
app_page_page3:
    path: /page
    controller: App\Controller\ArticleController::home

    
    # the "app_page_number" route name is not important yet
app_page_page4:
    path: /page/{find catégory}
    controller: App\Controller\Page2::articles plongee

 # the "app_page_number" route name is not important yet
app_page_page5:
    path: /page/{find catégory}
    controller: App\Controller\Page2::articles apnee


  

  
